### ISSUE TITLE
Mod is incompatible with U8.2

### ISSUE THREAD

**Issue by NiveusLuna** [Scordium/Hotterbars#1]
Mod is incompatible with Satisfactory Update 8.2 as released to the Early Access branch.

When Satisfactory is started with Hotterbars 1.0.1 enabled, the following error message pops up:

> Plugin 'KeybindableHotbar' failed to load because module 'KeybindableHotbar' could not be loaded.  There may be an operating system error or the module may not be properly set up.

The game then exits.

**Comment by Scordium** [comment]
Updated.
